INSERT INTO SOURCE.TABLE_ALL_TYPES(COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN6,COLUMN7) VALUES ('TEST1',1,CURRENT_DATE,'test',CURRENT_TIMESTAMP,1);
INSERT INTO SOURCE.TABLE_ALL_TYPES(COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN6,COLUMN7) VALUES ('TEST2',1,CURRENT_DATE,'test',CURRENT_TIMESTAMP,2);
INSERT INTO SOURCE.TABLE_ALL_TYPES(COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN6,COLUMN7) VALUES ('TEST3',1,CURRENT_DATE,'test',CURRENT_TIMESTAMP,3);
INSERT INTO SOURCE.TABLE_ALL_TYPES(COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN6,COLUMN7) VALUES ('TEST4',1,CURRENT_DATE,'test',CURRENT_TIMESTAMP,4);
COMMIT;