INSERT INTO TARGET.TABLE_ALL_TYPES(COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN6,COLUMN7) VALUES ('TEST11',1,CURRENT_DATE-1,'test',CURRENT_TIMESTAMP,1);
INSERT INTO TARGET.TABLE_ALL_TYPES(COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN6,COLUMN7) VALUES ('TEST22',1,CURRENT_DATE-1,'test',CURRENT_TIMESTAMP,1);
INSERT INTO TARGET.TABLE_ALL_TYPES(COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN6,COLUMN7) VALUES ('TEST33',1,CURRENT_DATE,'test',CURRENT_TIMESTAMP,1);
INSERT INTO TARGET.TABLE_ALL_TYPES(COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN6,COLUMN7) VALUES ('TEST44',1,CURRENT_DATE,'test',CURRENT_TIMESTAMP,1);
COMMIT;